window.RN_PRODUCTS = {
  'fermento-iogurte': {
    id: 'fermento-iogurte',
    name: 'Fermento para Iogurte Fermentação Rápida',
    shortDesc: 'Fermento para iogurte do tipo fermentação rápida! Produza iogurtes cremosos com segurança.',
    price: 4.88,
    brand: 'Ciência do Leite',
    ref: 'PRDD1088',
    image: 'fermento',
    type: 'fermento',
    volumes: ['20 Litros', '50 Litros', '100 Litros', '150 Litros', '200 Litros', '250 Litros', '300 Litros', '500 Litros', '1.000 Litros'],
    rating: 5,
    reviews: 3
  },
  'fermento-parmesao': {
    id: 'fermento-parmesao',
    name: 'Fermento para Parmesão',
    shortDesc: 'Cultura láctea selecionada para parmesão e queijos duros.',
    price: 178.5,
    brand: 'Ciência do Leite',
    ref: 'PRDD1142',
    image: 'fermento',
    type: 'fermento',
    volumes: ['20 Litros', '50 Litros', '100 Litros', '200 Litros', '500 Litros'],
    rating: 5,
    reviews: 12
  },
  'fermento-mussarela': {
    id: 'fermento-mussarela',
    name: 'Fermento para Mussarela Fermentação Lenta',
    shortDesc: 'Fermento para Mussarela do tipo fermentação lenta! Faça uma mussarela deliciosa!',
    price: 4.88,
    brand: 'Ciência do Leite',
    ref: 'PRDD1172',
    image: 'fermento',
    type: 'fermento',
    volumes: ['20 Litros', '50 Litros', '100 Litros', '150 Litros', '200 Litros', '250 Litros', '300 Litros', '500 Litros', '1.000 Litros'],
    rating: 5,
    reviews: 8
  },
  'fermento-minas': {
    id: 'fermento-minas',
    name: 'Fermento para Queijo Minas',
    shortDesc: 'Cultura ideal para queijo minas padrão e meia cura.',
    price: 62,
    brand: 'Ciência do Leite',
    ref: 'PRDD1190',
    image: 'fermento',
    type: 'fermento',
    volumes: ['20 Litros', '50 Litros', '100 Litros', '150 Litros', '200 Litros'],
    rating: 4,
    reviews: 2
  },
  'tanque-100': {
    id: 'tanque-100',
    name: 'Tanque de Queijo 100 Litros',
    shortDesc: 'Tanque em inox para produção artesanal de queijos.',
    price: 8715,
    brand: 'Rica Nata',
    ref: 'EQP100',
    image: 'tanque',
    type: 'simple',
    rating: 0,
    reviews: 0
  },
  'tanque-200': {
    id: 'tanque-200',
    name: 'Tanque de Queijo 200 Litros',
    shortDesc: 'Capacidade ampliada para pequenas queijarias.',
    price: 12450,
    brand: 'Rica Nata',
    ref: 'EQP200',
    image: 'tanque',
    type: 'simple',
    rating: 5,
    reviews: 5
  },
  'tanque-50': {
    id: 'tanque-50',
    name: 'Tanque de Queijo 50 Litros',
    shortDesc: 'Compacto e ideal para iniciantes.',
    price: 5890,
    brand: 'Rica Nata',
    ref: 'EQP050',
    image: 'tanque',
    type: 'simple',
    rating: 5,
    reviews: 3
  },
  'apostila-doce-leite': {
    id: 'apostila-doce-leite',
    name: 'Apostila para Doce de Leite e Requeijão',
    shortDesc: 'Passo a passo ilustrado com receitas testadas.',
    price: 61.95,
    brand: 'Rica Nata',
    ref: 'APO001',
    image: 'apostila',
    type: 'simple',
    rating: 5,
    reviews: 22
  },
  'apostila-artesanal': {
    id: 'apostila-artesanal',
    name: 'Apostila Queijos Artesanais',
    shortDesc: 'Técnicas para queijos artesanais de qualidade.',
    price: 61.95,
    brand: 'Rica Nata',
    ref: 'APO002',
    image: 'apostila',
    type: 'simple',
    rating: 5,
    reviews: 18
  },
  'apostila-iogurte': {
    id: 'apostila-iogurte',
    name: 'Apostila Iogurtes e Fermentados',
    shortDesc: 'Receitas de iogurtes, coalhada e fermentados lácteos.',
    price: 61.95,
    brand: 'Rica Nata',
    ref: 'APO003',
    image: 'apostila',
    type: 'simple',
    rating: 5,
    reviews: 9
  },
  'coalho-liquido': {
    id: 'coalho-liquido',
    name: 'Coalho Líquido 500 ml',
    shortDesc: 'Coagulante para queijos frescos e minas.',
    price: 42.9,
    brand: 'Rica Nata',
    ref: 'ING042',
    image: 'fermento',
    type: 'simple',
    rating: 5,
    reviews: 31,
    upsell: true
  },
  'termometro-sonda': {
    id: 'termometro-sonda',
    name: 'Termômetro Digital de Sonda',
    shortDesc: 'Precisão na pasteurização e coagulação.',
    price: 112.5,
    brand: 'Rica Nata',
    ref: 'ACC112',
    image: 'acessorio',
    type: 'simple',
    rating: 5,
    reviews: 15,
    upsell: true
  }
};
